// <auto-generated />
using System;
using InventoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123123426_UpdateProductSeedDataWithImages")]
    partial class UpdateProductSeedDataWithImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Storage",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5190),
                            Description = "Adjustable shelves for customized storage",
                            ImageUrl = "https://images.unsplash.com/photo-1594620302200-9a762244a156?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse A-1",
                            MinimumStock = 20,
                            Name = "BILLY Bookcase",
                            Price = 79.99m,
                            SKU = "BILLY-001",
                            StockQuantity = 150,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5190)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5190),
                            Description = "3-seat sofa with removable washable cover",
                            ImageUrl = "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse B-3",
                            MinimumStock = 5,
                            Name = "EKTORP Sofa",
                            Price = 599.99m,
                            SKU = "EKTORP-001",
                            StockQuantity = 25,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5190)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tables",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5190),
                            Description = "Easy to assemble side table",
                            ImageUrl = "https://images.unsplash.com/photo-1617097900219-2d6c81ecb60f?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse A-2",
                            MinimumStock = 30,
                            Name = "LACK Coffee Table",
                            Price = 49.99m,
                            SKU = "LACK-001",
                            StockQuantity = 200,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5190)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bedroom",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200),
                            Description = "Queen size bed frame with storage boxes",
                            ImageUrl = "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse C-1",
                            MinimumStock = 10,
                            Name = "MALM Bed Frame",
                            Price = 299.99m,
                            SKU = "MALM-001",
                            StockQuantity = 15,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            Id = 5,
                            Category = "Storage",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200),
                            Description = "4x4 shelving unit, perfect for storage boxes",
                            ImageUrl = "https://images.unsplash.com/photo-1595428774223-ef52624120d2?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse A-1",
                            MinimumStock = 15,
                            Name = "KALLAX Shelf Unit",
                            Price = 129.99m,
                            SKU = "KALLAX-001",
                            StockQuantity = 80,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            Id = 6,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200),
                            Description = "Comfortable armchair with bent wood frame",
                            ImageUrl = "https://images.unsplash.com/photo-1567538096630-e0c55bd6374c?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse B-2",
                            MinimumStock = 8,
                            Name = "POÄNG Armchair",
                            Price = 149.99m,
                            SKU = "POANG-001",
                            StockQuantity = 45,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            Id = 7,
                            Category = "Bedroom",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200),
                            Description = "8-drawer dresser in solid wood",
                            ImageUrl = "https://images.unsplash.com/photo-1558998966-079c4dbe6fd9?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse C-2",
                            MinimumStock = 5,
                            Name = "HEMNES Dresser",
                            Price = 399.99m,
                            SKU = "HEMNES-001",
                            StockQuantity = 20,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            Id = 8,
                            Category = "Tables",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200),
                            Description = "Ash veneer dining table, seats 4-6 people",
                            ImageUrl = "https://images.unsplash.com/photo-1617806118233-18e1de247200?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse A-3",
                            MinimumStock = 8,
                            Name = "LISABO Dining Table",
                            Price = 279.99m,
                            SKU = "LISABO-001",
                            StockQuantity = 30,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5200)
                        },
                        new
                        {
                            Id = 9,
                            Category = "Lighting",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210),
                            Description = "Adjustable floor lamp, perfect for reading",
                            ImageUrl = "https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse B-1",
                            MinimumStock = 15,
                            Name = "RANARP Floor Lamp",
                            Price = 89.99m,
                            SKU = "RANARP-001",
                            StockQuantity = 60,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210)
                        },
                        new
                        {
                            Id = 10,
                            Category = "Kitchen",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210),
                            Description = "5-piece stainless steel cookware set",
                            ImageUrl = "https://images.unsplash.com/photo-1584990347449-39e4e37260d9?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse D-1",
                            MinimumStock = 10,
                            Name = "VARDAGEN Cookware Set",
                            Price = 199.99m,
                            SKU = "VARDAGEN-001",
                            StockQuantity = 40,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210)
                        },
                        new
                        {
                            Id = 11,
                            Category = "Bedroom",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210),
                            Description = "Pine wood nightstand with 2 drawers",
                            ImageUrl = "https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse C-1",
                            MinimumStock = 12,
                            Name = "TARVA Nightstand",
                            Price = 69.99m,
                            SKU = "TARVA-001",
                            StockQuantity = 55,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210)
                        },
                        new
                        {
                            Id = 12,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210),
                            Description = "5-seat corner sofa with chaise",
                            ImageUrl = "https://images.unsplash.com/photo-1550581190-9c1c48d21d6c?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse B-3",
                            MinimumStock = 3,
                            Name = "VIMLE Corner Sofa",
                            Price = 1299.99m,
                            SKU = "VIMLE-001",
                            StockQuantity = 8,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210)
                        },
                        new
                        {
                            Id = 13,
                            Category = "Storage",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210),
                            Description = "Utility cart with wheels, perfect for kitchen or office",
                            ImageUrl = "https://images.unsplash.com/photo-1588471980726-8346cb477a33?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse A-2",
                            MinimumStock = 25,
                            Name = "RÅSKOG Cart",
                            Price = 39.99m,
                            SKU = "RASKOG-001",
                            StockQuantity = 120,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210)
                        },
                        new
                        {
                            Id = 14,
                            Category = "Decor",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210),
                            Description = "Large walnut veneer framed mirror",
                            ImageUrl = "https://images.unsplash.com/photo-1618220179428-22790b461013?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse D-2",
                            MinimumStock = 5,
                            Name = "STOCKHOLM Mirror",
                            Price = 249.99m,
                            SKU = "STOCKHOLM-001",
                            StockQuantity = 18,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5210)
                        },
                        new
                        {
                            Id = 15,
                            Category = "Storage",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5220),
                            Description = "Industrial style TV bench with metal frame",
                            ImageUrl = "https://images.unsplash.com/photo-1593359677879-a4bb92f829d1?w=400&h=400&fit=crop",
                            IsActive = true,
                            Location = "Warehouse A-3",
                            MinimumStock = 8,
                            Name = "FJÄLLBO TV Unit",
                            Price = 179.99m,
                            SKU = "FJALLBO-001",
                            StockQuantity = 35,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5220)
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PerformedBy = "John Doe",
                            ProductId = 1,
                            Quantity = 50,
                            Reference = "PO-001",
                            TransactionDate = new DateTime(2025, 11, 13, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5240),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            PerformedBy = "Jane Smith",
                            ProductId = 1,
                            Quantity = 10,
                            Reference = "SO-001",
                            TransactionDate = new DateTime(2025, 11, 18, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5240),
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            PerformedBy = "John Doe",
                            ProductId = 2,
                            Quantity = 15,
                            Reference = "PO-002",
                            TransactionDate = new DateTime(2025, 11, 16, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5250),
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            PerformedBy = "Jane Smith",
                            ProductId = 3,
                            Quantity = 25,
                            Reference = "SO-002",
                            TransactionDate = new DateTime(2025, 11, 21, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5250),
                            Type = 1
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Stockholm, Sweden",
                            ContactPerson = "Erik Larsson",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5100),
                            Email = "erik@scandi.com",
                            IsActive = true,
                            Name = "Scandinavian Furniture Co.",
                            Phone = "+46-123-456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gdansk, Poland",
                            ContactPerson = "Anna Kowalski",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 34, 26, 278, DateTimeKind.Utc).AddTicks(5100),
                            Email = "anna@baltic.com",
                            IsActive = true,
                            Name = "Baltic Wood Supplies",
                            Phone = "+48-987-654"
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.HasOne("InventoryAPI.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryAPI.Models.StockTransaction", b =>
                {
                    b.HasOne("InventoryAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryAPI.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
