// <auto-generated />
using System;
using InventoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251123122954_AddImageUrlToProduct")]
    partial class AddImageUrlToProduct
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MinimumStock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupplierId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.HasIndex("SupplierId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Storage",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8650),
                            Description = "Adjustable shelves",
                            IsActive = true,
                            Location = "Warehouse A-1",
                            MinimumStock = 20,
                            Name = "BILLY Bookcase",
                            Price = 79.99m,
                            SKU = "BILLY-001",
                            StockQuantity = 150,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8650)
                        },
                        new
                        {
                            Id = 2,
                            Category = "Furniture",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8660),
                            Description = "3-seat sofa with removable cover",
                            IsActive = true,
                            Location = "Warehouse B-3",
                            MinimumStock = 5,
                            Name = "EKTORP Sofa",
                            Price = 599.99m,
                            SKU = "EKTORP-001",
                            StockQuantity = 25,
                            SupplierId = 1,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8660)
                        },
                        new
                        {
                            Id = 3,
                            Category = "Tables",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8660),
                            Description = "Easy to assemble",
                            IsActive = true,
                            Location = "Warehouse A-2",
                            MinimumStock = 30,
                            Name = "LACK Coffee Table",
                            Price = 49.99m,
                            SKU = "LACK-001",
                            StockQuantity = 200,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8660)
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bedroom",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8660),
                            Description = "Queen size with storage",
                            IsActive = true,
                            Location = "Warehouse C-1",
                            MinimumStock = 10,
                            Name = "MALM Bed Frame",
                            Price = 299.99m,
                            SKU = "MALM-001",
                            StockQuantity = 15,
                            SupplierId = 2,
                            UpdatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8660)
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.StockTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ProductId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reference")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("StockTransactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PerformedBy = "John Doe",
                            ProductId = 1,
                            Quantity = 50,
                            Reference = "PO-001",
                            TransactionDate = new DateTime(2025, 11, 13, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8680),
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            PerformedBy = "Jane Smith",
                            ProductId = 1,
                            Quantity = 10,
                            Reference = "SO-001",
                            TransactionDate = new DateTime(2025, 11, 18, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8680),
                            Type = 1
                        },
                        new
                        {
                            Id = 3,
                            PerformedBy = "John Doe",
                            ProductId = 2,
                            Quantity = 15,
                            Reference = "PO-002",
                            TransactionDate = new DateTime(2025, 11, 16, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8690),
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            PerformedBy = "Jane Smith",
                            ProductId = 3,
                            Quantity = 25,
                            Reference = "SO-002",
                            TransactionDate = new DateTime(2025, 11, 21, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8690),
                            Type = 1
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Supplier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Suppliers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Stockholm, Sweden",
                            ContactPerson = "Erik Larsson",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8580),
                            Email = "erik@scandi.com",
                            IsActive = true,
                            Name = "Scandinavian Furniture Co.",
                            Phone = "+46-123-456"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Gdansk, Poland",
                            ContactPerson = "Anna Kowalski",
                            CreatedAt = new DateTime(2025, 11, 23, 12, 29, 54, 201, DateTimeKind.Utc).AddTicks(8590),
                            Email = "anna@baltic.com",
                            IsActive = true,
                            Name = "Baltic Wood Supplies",
                            Phone = "+48-987-654"
                        });
                });

            modelBuilder.Entity("InventoryAPI.Models.Product", b =>
                {
                    b.HasOne("InventoryAPI.Models.Supplier", "Supplier")
                        .WithMany("Products")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("InventoryAPI.Models.StockTransaction", b =>
                {
                    b.HasOne("InventoryAPI.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("InventoryAPI.Models.Supplier", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
